### ISSUE TITLE
Add option to preserve disk cache between restarts

### ISSUE THREAD

**Issue by bdutro** [rtyle/gstfs-ng#1]
It would be nice if we could optionally preserve the disk cache between restarts. My music library doesn't change that often, but every time I remount the volume I have to re-convert everything all over again.

**Comment by rtyle** [comment]
This is what the **cachePersist** option is for.
From the man page:

**cachePersist=**_PERSIST_
Specify a directory where cached images will persist after they are
removed from memory.
This persistent cache will last between **gstfs-ng** sessions
so that transcoding need not be redone.
Cached files in the _PERSIST_ directory are named
using **stat -c %d.%i.%Y** reported identifiers from the referencing source file.
Note that the reference will not break if the source file is moved or
renamed but will if it is modified (as it should be).
At the beginning of a **gstfs-ng** session, the _PERSIST_ directory
will be purged of unreferenced images.

**Comment by bdutro** [comment]
My apologies, I misread the manpage. I was also using a network share in the past that probably changed device numbers with every boot. I've moved to a different setup now and the cache appears to be persistent between boots.

**Comment by rtyle** [comment]
I am glad it works for you.
I have a server that has my SOURCE directory and multiple gstfs-ng TARGET directories.
These are exported to various clients using NFS and SMB (samba).
Yes, if the device number (%d), the inode number (%i) or modification time (%Y) of a source file changes it will invalidate any previously cached transcoding -- requiring a new transcoding.
These orphans are cleaned up when gstfs-ng starts.
See NFS inode notes on man page.
